/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ruOARMjKr0G
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import { SummaryCard } from "../cards/SummaryCard";
import { projectList } from "@/app/.data/projectList";
import { SummaryFilterNav } from "../navbars/SummaryFilterNav";
import Link from "next/link";
export function SummaryLayout() {
	const data = projectList;
	return (
		<>
			<SummaryFilterNav />

			<main className='flex min-h-screen flex-col items-center  p-4'>
				<div className='grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4'>
					{data.map((project) => (
						<Link
							href={{
								pathname: "/projects",
								query: { project: project.queryParam },
							}}
						>
							<SummaryCard project={project} />
						</Link>
					))}
					<div className='bg-background rounded-lg shadow-md p-6'>
						<h3 className='text-lg font-semibold mb-2'>Card 3</h3>
						<p className='text-muted-foreground mb-4'>
							This is a third summary card with a title, description, and a
							button.
						</p>
						<Button size='sm'>Learn More</Button>
					</div>
					<div className='bg-background rounded-lg shadow-md p-6'>
						<h3 className='text-lg font-semibold mb-2'>Card 4</h3>
						<p className='text-muted-foreground mb-4'>
							This is a fourth summary card with a title, description, and a
							button.
						</p>
						<Button size='sm'>Learn More</Button>
					</div>
				</div>
			</main>
		</>
	);
}
