import { ProjectList } from "../types/type";

export const projectList: ProjectList[] = [
	{
		id: 1,
		role: "Full Stack Developer",
		contributions: "Frontend, Backend, Database",
		queryParam: "yet-another-social-media-app",
		name: "Yet Another Social Media App",
		blurb: "Social mnedia app",
		description:
			"Social media app that allows users to post, like, and comment on posts.",
		functioning: false,
		note: [{ id: 1, title: "Vercel down", text: "Vercel down" }],
		progress: 100,
		image: "Project Image",
		url: "https://yet-another-social-media-app.vercel.app/",
		github: "https://github.com/Glade3796/yet-another-social-media-app",
		tech: ["JS", "React", "postgreSQL", "Express", "CSS", "Vercel"],
		lastUpdate: "2024-01-01",
		started: "2023-08-01",
		completed: true,
		completedDate: "2021-09-01",
		screenshot: "/placeholder.svg",
		type: ["Social Media", "CRUD", "Blog", "Database", "Authentication"],
	},
	{
		id: 2,
		role: "Full Stack Developer",
		contributions: "Frontend, Backend, Database",
		queryParam: "l-lorum",
		name: "L'forum",
		blurb: "Forum app",

		description:
			"Full Stack react app that allows users to post, like, and comment on posts.",
		functioning: true,
		note: [
			{ id: 1, title: "Vercel down", text: "Vercel down" },
			{ id: 2, title: "issues", text: "issues" },
		],
		progress: 100,
		image: "Project Image",
		url: "https://lforum.onrender.com/",
		github: "https://github.com/Glade3796/l-lorum",
		tech: ["Vite", "HTML", "Express", "JS", "CSS", "HTML", "postgreSQL"],
		lastUpdate: "2023-06-01",
		started: "2023-05-01",
		completed: true,
		completedDate: "2021-09-01",
		screenshot: "/placeholder.svg",
		type: ["Social Media", "Forum", "Blog", "CRUD"],
	},
	{
		id: 3,
		role: "Full Stack Developer",
		contributions: "Frontend, Backend, Database",
		queryParam: "community-app",
		name: "Community App",
		blurb: "Social mnedia app",

		description:
			"Full Stack react app that allows users to post, like, and comment on posts.",
		functioning: true,
		note: [
			{ id: 1, title: "Vercel down", text: "Vercel down" },
			{ id: 2, title: "issues", text: "issues" },
		],
		progress: 77,
		image: "Project Image",
		url: "https://lforum.onrender.com/",
		github: "https://github.com/Glade3796/l-lorum",
		tech: ["NextJs", "React", "postgreSQL", "Vercel"],
		lastUpdate: "2024-02-01",
		started: "2023-12-01",
		completed: false,
		completedDate: "",
		screenshot: "/placeholder.svg",
		type: ["Social Media", "Forum", "Blog", "CRUD"],
	},
	{
		id: 4,
		role: "Freelance Full Stack Developer - junior",
		contributions: "Specific components",
		queryParam: "applicably-ai",
		name: "Applicably AI",
		blurb: "CV Builder & customer management",
		description:
			"Full Stack react app that allows users to post, like, and comment on posts.",
		functioning: false,
		note: [
			{ id: 1, title: "Vercel down", text: "Vercel down" },
			{ id: 2, title: "issues", text: "issues" },
		],
		progress: 15,
		image: "Project Image",
		url: "https://lforum.onrender.com/",
		github: "https://github.com/Glade3796/l-lorum",
		tech: ["NextJs", "React", "OpenAI", "postgreSQL", "Radix"],
		lastUpdate: "2024-08-01",
		started: "2025-03-01",
		completed: false,
		completedDate: "2021-09-01",
		screenshot: "/placeholder.svg",
		type: ["Social Media", "Freelance", "AI"],
	},
	{
		id: 5,
		role: "Full Stack Developer",
		contributions: "Frontend, Backend, Database",
		queryParam: "save-the-planet-v2",
		name: "Save The Planet V2",
		blurb: "Eco game",

		description: "Cookie clicker cloner with a twist. Try to save the world.",
		functioning: false,
		note: [
			{ id: 1, title: "Vercel down", text: "Vercel down" },
			{ id: 2, title: "issues", text: "issues" },
		],
		progress: 50,
		image: "Project Image",
		url: "https://lforum.onrender.com/",
		github: "https://github.com/Glade3796/l-lorum",
		tech: ["Vite", "React", "Express", "postgreSQL"],
		lastUpdate: "2024-03-01",
		started: "2024-02-01",
		completed: false,
		completedDate: "2021-09-01",
		screenshot: "/placeholder.svg",
		type: ["Game"],
	},
	{
		id: 6,
		role: "Full Stack Developer",
		contributions: "Frontend, Backend, Database",
		queryParam: "save-the-planet-v1",
		name: "Save The Planet V1",
		blurb: "Eco game",

		description: "Cookie clicker cloner with a twist. Try to save the world.",
		functioning: false,
		note: [
			{ id: 1, title: "Vercel down", text: "Vercel down" },
			{ id: 2, title: "issues", text: "issues" },
		],
		progress: 100,
		image: "Project Image",
		url: "https://lforum.onrender.com/",
		github: "https://github.com/Glade3796/l-lorum",
		tech: ["Vite", "React", "Express", "postgreSQL"],
		lastUpdate: "2021-09-01",
		started: "2021-08-01",
		completed: true,
		completedDate: "2021-09-01",
		screenshot: "/placeholder.svg",
		type: ["Game"],
	},
	{
		id: 7,
		role: "Full Stack Developer",
		contributions: "Frontend, Backend, Database",
		queryParam: "spacey",
		name: "SpaceY",
		blurb: "Static site in html and css",

		description: "Basic website built with html and css.",
		functioning: true,
		note: [
			{ id: 1, title: "Vercel down", text: "Vercel down" },
			{ id: 2, title: "issues", text: "issues" },
		],
		progress: 100,
		image: "Project Image",
		url: "https://lforum.onrender.com/",
		github: "https://github.com/Glade3796/l-lorum",
		tech: ["Vite", "HTML", "JS", "CSS"],
		lastUpdate: "2021-09-01",
		started: "2021-08-01",
		completed: true,
		completedDate: "2021-09-01",
		screenshot: "/placeholder.svg",
		type: ["Gallery", "Website", "Static"],
	},
	{
		id: 8,
		role: "Full Stack Developer",
		contributions: "Frontend, Backend, Database",
		queryParam: "yoga-builder",
		name: "Yoga Builder",
		blurb: "Eco game",

		description: "App to help design yoga routines.",
		functioning: false,
		note: [
			{ id: 1, title: "Vercel down", text: "Vercel down" },
			{ id: 2, title: "issues", text: "issues" },
		],
		progress: 5,
		image: "Project Image",
		url: "https://lforum.onrender.com/",
		github: "https://github.com/Glade3796/l-lorum",
		tech: ["Vite", "React", "Express", "postgreSQL"],
		lastUpdate: "2021-09-01",
		started: "2021-08-01",
		completed: false,
		completedDate: "2021-09-01",
		screenshot: "/placeholder.svg",
		type: ["Other"],
	},
];
